### ISSUE TITLE
Failed installation: `Error: callback() can only be called once.`

### ISSUE THREAD

**Issue by feimosi** [GoogleChromeLabs/simplehttp2server#31]
I'm getting the following error when running `npm install -g simplehttp2server`:

```
/usr/bin/simplehttp2server -> /usr/lib/node_modules/simplehttp2server/cli.js

> simplehttp2server@2.0.0 postinstall /usr/lib/node_modules/simplehttp2server
> node lib/install.js

/usr/lib/node_modules/simplehttp2server/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/simplehttp2server/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/simplehttp2server/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/simplehttp2server/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
```

Tested on the latest versions of node (8.1.3) and npm (5.0.4).
I'm running Arch Linux.

**Comment by malaniz** [comment]
The same here with npm 5.1.0 and node 8.1.2 in Archlinux too.

**Comment by surma** [comment]
Interesting. I‘ll investigate soon, probably can’t this week.

Pinging @1000ch to take a look if he has time.

**Comment by porfirioribeiro** [comment]
I guess it is a permissions problem, i had the same problem, fixed it using a global folder in my home folder
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by feimosi** [comment]
I confirm, that resolves the issue :+1:

**Comment by JojOatXGME** [comment]
I just wanted to mention that the issue does still exist.

**Comment by dandv** [comment]
This issue still exist, and it's blocking a lot of people from installing preact-cli, which I believe @slightlyoff and @owencm would not be very happy about ;)

https://github.com/developit/preact-cli/issues/191
https://github.com/developit/preact-cli/issues/406
https://github.com/developit/preact-cli/issues/424

**Comment by surma** [comment]
Pinging @1000ch

**Comment by surma** [comment]
This issue is most likely with the npm wrapper: https://github.com/1000ch/simplehttp2server

**Comment by o-ayoub** [comment]
Thank to **porfirioribeiro**, 

I confirm that resolve the issue for me.

**Comment by mindplay-dk** [comment]
To others looking for a solution, [changing npm's default directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory) fixed it for me.

**Comment by matthewstewart** [comment]
Switching my node version to 7.10 for the install worked for me.
